version: '3.3'

services:
  server:
    image: kurento/kurento-media-server
    container_name: kms
    volumes:
      - .:/src/kms/
    ports:
      - 8888:8888
  client1:
    build: .
    container_name: client1
    command: python manage.py runserver 0.0.0.0:8080
    ports:
      - "8080:8080"
    depends_on:
      - server

  client2:
    build: .
    container_name: client2
    command: python manage.py runserver 0.0.0.0:8081
    ports:
      - "8081:8081"
    depends_on:
      - server